### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/devel#150]
There's been quite a few issues closed since the last release including a few around PHP 8.1.

Please @quicksketch , @jenlampton , @alanmels - can we have a new release?

**Comment by jenlampton** [comment]
I don't think this is ready for a release as-is, we may need to revert some
changes around the library update. I'd be willing to work on that today.

**Comment by yorkshire-pudding** [comment]
Any progress @jenlampton ?

**Comment by yorkshire-pudding** [comment]
Any further forwards @jenlampton? Am I right in thinking that #135 is the problem?
Incidentally, the current HEAD version helped me find the cause of the issue in https://github.com/backdrop/backdrop-issues/issues/5866 whereas the released version crashed when trying to debug.

**Comment by jenlampton** [comment]
The problem was https://github.com/backdrop-contrib/devel/issues/102, which I got excited and merged to quickly, and broke 1.x.1.x.  I've pulled out that change so we can polish it up a little more, but I am comfortable making a new release that includes all the other fixes, including some additional ones for PHP 8.1.
