### ISSUE TITLE
Check if taxonomy.module is enabled before generating terms/vocabularies.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/devel#22]
I've been messing with the code trying to mimic the menu and menu item generation form in order to convert the vocabulary select box in the term generation tab to a checkbox list instead. I've noticed that we check whether the menu.module is enabled before we render the list of menus (https://github.com/backdrop-contrib/devel/blob/1.x-1.x/devel_generate/devel_generate.module#L392). Doesn't it make sense to also check if taxonomy.module is enabled before rendering vocabularies too?

**Comment by quicksketch** [comment]
I think we already do this because we check if taxonomy module exists in `hook_menu()`: https://github.com/backdrop-contrib/devel/blob/1.x-1.x/devel_generate/devel_generate.module#L38

The entire pages for generate vocabs/terms isn't shown at all if the module doesn't exist. Menus are slightly different in that the concept of a menu still exists even without menu.module. That module just enables the creation of new menus and custom menu items.
