### ISSUE TITLE
Should we check whether certain modules providing fields are enabled?

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/devel#26]
I don't see any if module exists checks before the functions that generate content. Do we actually need to do something like that or do we assume that if such a field exists in the content type, then the respective module must be enabled? Just curious that's all.

**Comment by quicksketch** [comment]
The code isn't perfectly clear, but we already only add field implementations for modules that exist. This bit of code is in `devel_generate_fields()`:

```
      $module = $field_types[$field['type']]['module'];

      // Include any support file that might exist for this field.
      if (in_array($module, array('comment', 'date', 'file', 'image', 'link', 'list', 'number', 'taxonomy', 'text'))) {
        // devel_generate implements on behalf of core and special friends.
        module_load_include('inc', 'devel_generate', "modules/$module.devel_generate");
      }
```

At first read, it might look like we're including all of those module implementations. But what's happening here is that the module name is being provided by the field for which we're generating content. So if this is an image field for example `$module = $field_types[$field['type']]['module']` will result in `image`. Then the `image.devel_generate.inc` file is included.

So while we don't explicitly check `if (module_exists('image')) {`, we don't need to, because the field already has told us it's owned by image.module.
