### ISSUE TITLE
Add a UI to enable theme_debug

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/devel#4]
There's an awesome new setting in backdrop (and Drupal) that allows people to see which template files they should be overriding. But in Backdrop core there's no UI. Devel should provide one.
- Add a checkbox to the devel settings page
- make sure config is updated appropriately. (system.core)

**Comment by klonos** [comment]
I started writing a copy of parts of the documentation in https://www.drupal.org/node/223440#theme-debug and just published [an initial handbook page](https://backdropcms.org/handbook/themer-guide/theme-debug-mode) under a new "Themer Guide" section I created for our handbook. I forgot why I started doing this, but I was pretty sure I saw a link either in a README file or while reviewing some code (sleep deprived for days). Anyways, before I go forth with filing in the rest of the details, I need someone to take a look at the document because it mentions drush commands that I am not sure they work in Backdrop (in which case we should remove these lines from the documentation page) and also a `theme_debug` variable that is supposed to go in the settings.php file, but again not sure because we switched to CMI.

**Comment by sentaidigital** [comment]
PR updated with a check to make sure Devel doesn't break BD < 1.5.0.

**Comment by MrHaroldA** [comment]
While the patch/PR above works perfectly, I think the description is lacking information.

![image](https://cloud.githubusercontent.com/assets/695291/21189511/3bb7c92e-c21f-11e6-8c68-ea987a6029a2.png)

Unless you accidentally look in the source, you'll never notice it's on.

**Comment by sentaidigital** [comment]
What should it say?

**Comment by klonos** [comment]
Something like this perhaps?:

> Displays all templates used to render each page as well as the locations of their respective template files. Useful for finding template suggestions when building a custom theme.

**Comment by jenlampton** [comment]
I don't like the word "Displays", that makes me think they will all be rendered or something. How about 

> Adds HTML comments containing information about the template files used to render each part of the page. Useful for finding template suggestions when building a custom theme.

**Comment by MrHaroldA** [comment]
It could also do with it's own fieldset instead of adding it to the general fieldset.

**Comment by sentaidigital** [comment]
> It could also do with it's own fieldset instead of adding it to the general fieldset.

It is sharing a fieldset with the one other item saved in `system.core` instead of `devel.settings`.

**Comment by sentaidigital** [comment]
Patch updated and pushed to the open PR.

**Comment by quicksketch** [comment]
Thanks @sentaidigital! I merged https://github.com/backdrop-contrib/devel/pull/28 before I found your PR. I'll combine both into a single approach.

**Comment by quicksketch** [comment]
This was fixed in https://github.com/backdrop-contrib/devel/commit/49a1f79ae486dd09486ab3ff9e6c7570d9201a9a, where I combined the two PRs #28 and #15.
