### ISSUE TITLE
`devel_menu_rebuild()` function missing

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/devel#54]
...between `devel_querylog_arguments()` and `devel_reinstall()` in `devel.pages.inc`:

```php
/**
 * Page callback: Clears the database, resetting the menu to factory defaults.
 */
function devel_menu_rebuild() {
  menu_rebuild();
  drupal_set_message(t('The menu router has been rebuilt.'));
  drupal_goto();
}
```

**Comment by quicksketch** [comment]
Perhaps this was removed because it's not used anywhere? Or perhaps now that admin_bar is part of core, it didn't make any sense for Devel module to provide duplicate functionality for rebuilding the menu when core provides that directly under `Home > Flush all caches > Menu`.

Please reopen if needed.
