### ISSUE TITLE
`devel_node_access_uninstall()` missing

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/devel#56]
The devel_node_access.install file is practically empty (only comments).

From the 7.x version:

```php
function devel_node_access_uninstall() {
  variable_del('devel_node_access_debug_mode');

  if (!module_exists('devel') && ($devel_menu = menu_load('devel'))) {
    // Delete the development menu.
    menu_delete($devel_menu);
  }
}
```

**Comment by quicksketch** [comment]
Backdrop does not add it's own menu, instead it puts Devel items in the main `/admin` path so that they show up in the admin bar. Since it doesn't create it's own menu, it doesn't need to clean it up on uninstall.

Please reopen if it's necessary for this to exist for another reason (e.g. the cross-porting you're doing). If needed we can re-add it to do other clean-up, even if it's not needed for menus.
