### ISSUE TITLE
Wrong function parameter for user_save() in devel_generate.inc

### ISSUE THREAD

**Issue by VasasA** [backdrop-contrib/devel#80]
There is a wrong function parameter for user_save() in devel_generate.inc line 107:
user_save($account, $edit);
I created a PR.

**Comment by klonos** [comment]
@VasasA please be careful. You have committed directly instead of creating a PR.

The change was small, and it makes sense; so no need to revert. But please be careful in the future. You see, all contrib maintainers have permissions to push/commit to all contrib projects. "With great power comes great responsibility" 🙂

**Comment by VasasA** [comment]
I'm sorry. I wanted to create only a PR.
I will be more careful.

**Comment by klonos** [comment]
Sorry for taking that long to come back to this. I have fixed things with https://github.com/backdrop-contrib/devel/commit/c9df5ae01720ce8d8f1033d6d8eb238520d263bb (respective commit for https://git.drupalcode.org/project/devel/commit/1d4e2ef295c76db89f30a52f52725afb8a43af2a)
